[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#4285F4"  # Google blue
backgroundColor = "#202124"
secondaryBackgroundColor = "#303134"
textColor = "#FFFFFF"
font = "sans serif"
